-- data.sql

INSERT INTO INSTITUTE_DETAILS (INSTITUTE_ID,INSTITUTE_NAME, INSTITUTE_LOCATION, INSTITUTE_EMAIL, INSTITUTE_CONTACT)
VALUES (1,'MGM COLLEGE OF CS & IT NANDED', 'NAMASKAR CHOWK, NANDED', 'MGMCOLLEGE@EDU.IN', '8596741425');

INSERT INTO INSTITUTE_DETAILS (INSTITUTE_ID,INSTITUTE_NAME, INSTITUTE_LOCATION, INSTITUTE_EMAIL, INSTITUTE_CONTACT)
VALUES (2,'G.H.RAISONI COLLEGE OF ENGG PUNE', 'WAGHOLI, PUNE', 'GHRAISONICOLLEGE@EDU.IN', '9635486248');

INSERT INTO INSTITUTE_DETAILS (INSTITUTE_ID,INSTITUTE_NAME, INSTITUTE_LOCATION, INSTITUTE_EMAIL, INSTITUTE_CONTACT)
VALUES (3,'D.Y.PATIL COLLEGE OF ENGG TALEGAON', 'TALEGAON, PUNE', 'DYPATILCOLLEGE@EDU.IN', '9517534568');

INSERT INTO INSTITUTE_DETAILS (INSTITUTE_ID,INSTITUTE_NAME, INSTITUTE_LOCATION, INSTITUTE_EMAIL, INSTITUTE_CONTACT)
VALUES (4,'LBS COLLEGE DHARMABAD', 'NEAR MAHADEV MANDIR, DHARMABAD', 'LBSCOLLEGE@EDU.IN', '9545852534');
