-- data.sql

INSERT INTO INSTITUTE_DETAILS (INSTITUTE_ID,INSTITUTE_NAME, INSTITUTE_LOCATION, INSTITUTE_EMAIL, INSTITUTE_CONTACT)
VALUES (1,'MGM COLLEGE OF CS & IT NANDED', 'NAMASKAR CHOWK, NANDED', 'MGMCOLLEGE@EDU.IN', '8596741425');

INSERT INTO INSTITUTE_DETAILS (INSTITUTE_ID,INSTITUTE_NAME, INSTITUTE_LOCATION, INSTITUTE_EMAIL, INSTITUTE_CONTACT)
VALUES (2,'G.H.RAISONI COLLEGE OF ENGG PUNE', 'WAGHOLI, PUNE', 'GHRAISONICOLLEGE@EDU.IN', '8596741425');

INSERT INTO INSTITUTE_DETAILS (INSTITUTE_ID,INSTITUTE_NAME, INSTITUTE_LOCATION, INSTITUTE_EMAIL, INSTITUTE_CONTACT)
VALUES (3,'D.Y.PATIL COLLEGE OF ENGG TALEGAON', 'TALEGAON, PUNE', 'DYPATILCOLLEGE@EDU.IN', '8596741425');

-- data.sql

--INSERT INTO INSTITUTE_DETAILS (INSTITUTE_ID,INSTITUTE_NAME, INSTITUTE_LOCATION, INSTITUTE_EMAIL, INSTITUTE_CONTACT)
--VALUES ('MGM COLLEGE OF CS & IT NANDED', 'NAMASKAR CHOWK, NANDED', 'MGMCOLLEGE@EDU.IN', '8596741425');

--INSERT INTO INSTITUTE_DETAILS (INSTITUTE_ID,INSTITUTE_NAME, INSTITUTE_LOCATION, INSTITUTE_EMAIL, INSTITUTE_CONTACT)
--VALUES ('G.H.RAISONI COLLEGE OF ENGG PUNE', 'WAGHOLI, PUNE', 'GHRAISONICOLLEGE@EDU.IN', '8596741425');

--INSERT INTO INSTITUTE_DETAILS (INSTITUTE_ID,INSTITUTE_NAME, INSTITUTE_LOCATION, INSTITUTE_EMAIL, INSTITUTE_CONTACT)
--VALUES ('D.Y.PATIL COLLEGE OF ENGG TALEGAON', 'TALEGAON, PUNE', 'DYPATILCOLLEGE@EDU.IN', '8596741425');
